# How to run in local
#
# pre-commit will also modify the files. Modifications need to be commited separately
#
# pip install pre-commit
# pre-commit install
# pre-commit run --all-files

# check-yaml - This hook checks yaml files for parseable syntax.
# end-of-file-fixer - Ensures that a file is either empty, or ends with one newline.
# trailing-whitespace - This hook trims trailing whitespace.
# check-ast - Simply check whether the files parse as valid python.
# requirements-txt-fixer - Sorts entries in requirements.txt
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: check-ast
    -   id: requirements-txt-fixer

# Black is the uncompromising Python code formatter. By using it, you agree to cede control over minutiae of hand-formatting.    
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black    

# Python code style and quality    
# -   repo: https://gitlab.com/PyCQA/flake8
#     rev: 3.8.4
#     hooks:
#     -   id: flake8

# Checks for dead code    
-   repo: https://github.com/asottile/dead
    rev: v1.3.0
    hooks:
    -   id: dead
